export const data = [
  { image: "https://www.dpreview.com/files/p/E~products/sony_slta58/shots/fc0cfe482f1a454d815855380c8f8cd9.png",
    name: "Sony Alpha 7M III",
    instance: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor tempor tellus",
    price: "$11,70",
    category: 1,
    sale: "yes",
  },

  { image: "https://www.dpreview.com/files/p/E~products/sony_slta58/shots/fc0cfe482f1a454d815855380c8f8cd9.png",
    name: "Sony Alpha 7M III",
    instance: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor tempor tellus",
    price: "$11,70",
    category: 2,
    sale: "yes",
  },

  { image: "https://www.dpreview.com/files/p/E~products/sony_slta58/shots/fc0cfe482f1a454d815855380c8f8cd9.png",
    name: "Sony Alpha 7M III",
    instance: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor tempor tellus",
    price: "$11,70",
    category: 3,
    sale: "yes",
  },

  { image: "https://www.dpreview.com/files/p/E~products/sony_slta58/shots/fc0cfe482f1a454d815855380c8f8cd9.png",
    name: "Sony Alpha 7M III",
    instance: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor tempor tellus",
    price: "$11,70",
    category: 4,
    sale: "yes",
  },

   { image: "https://www.dpreview.com/files/p/E~products/sony_slta58/shots/fc0cfe482f1a454d815855380c8f8cd9.png",
    name: "Sony Alpha 7M III",
    instance: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor tempor tellus",
    price: "$11,70",
    category: "Laptop",
    sale: "yes",
  },

   { image: "https://www.dpreview.com/files/p/E~products/sony_slta58/shots/fc0cfe482f1a454d815855380c8f8cd9.png",
    name: "Sony Alpha 7M III",
    instance: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor tempor tellus",
    price: "$11,70",
    category: "Laptop",
    sale: "yes",
  },

   { image: "https://www.dpreview.com/files/p/E~products/sony_slta58/shots/fc0cfe482f1a454d815855380c8f8cd9.png",
    name: "Sony Alpha 7M III",
    instance: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor tempor tellus",
    price: "$11,70",
    category: "Laptop",
    sale: "yes",
  },

   { image: "https://www.dpreview.com/files/p/E~products/sony_slta58/shots/fc0cfe482f1a454d815855380c8f8cd9.png",
    name: "Sony Alpha 7M III",
    instance: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor tempor tellus",
    price: "$11,70",
    category: "Gear",
    sale: "yes",
  },

]